export { default as NavList } from "./nav-list"
export { default as TourismCategory } from "./tourism-category"
export { default as SimpleSplide } from "./simple-splide"
export { default as ContactsForm } from "./contacts"
export { default as EditorGallary } from "./rent-history"
export { default as AnimationAbout } from "./about"